apiVersion: apps/v1
kind: Deployment
metadata:
  name: quagga2
  labels:
    app: quagga2
spec:
  selector:
    matchLabels:
      app: quagga2
  template:
    metadata:
      labels:
        app: quagga2
    spec: 
      containers:
      - image: cameronbrunner/k8s-quagga:latest
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        name: quagga
        env:
        - name: K8S_QUAGGA_INTERFACE
          value: eth0
        - name: K8S_QUAGGA_PORTALNET
          value: 172.17.0.0/16
        - name: K8S_QUAGGA_CONTAINERNET
          value: 172.17.0.0/16
        - name: K8S_QUAGGA_PORTALGW
          value: 192.168.64.0/24
        - name: K8S_QUAGGA_HOMENET
          value: 192.168.64.0/24
        - name: K8S_QUAGGA_ROUTERID
          value: 192.168.64.2
        - name: K8S_QUAGGA_PASSWORD
          value: ospf1
      restartPolicy: Always
      hostNetwork: true
